apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-12-factor-app.fullname" . }}
  labels:
    {{- include "demo-12-factor-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
