name: CI Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/demo-12-factor-app
          tags: |
            type=ref,event=branch
            type=sha
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Helm values with image tag (GitOps trigger)
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_TAG: sha-${{ github.sha }}
        run: |
          echo "Setting image tag to $IMAGE_TAG"
          docker run --rm -v "$PWD":/work -w /work -e IMAGE_TAG="$IMAGE_TAG" --user "$(id -u):$(id -g)" mikefarah/yq \
            -i '.image.tag = env(IMAGE_TAG)' helm/demo-12-factor-app/values.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/demo-12-factor-app/values.yaml
          git commit -m "ci: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push
